### ISSUE TITLE
Please add rowlock_cleaner.c to patch/sqlumdash.patch

### ISSUE THREAD

**Issue by iwamatsu** [sqlumdash/sqlumdash#1]
Hi, 
I tried building this software but it fails.
I checked the error,  there is no patch of rowlock_cleaner.c in patch/sqlumdash.patch.
Could you add this?

```
make: *** No rule to make target '/t/sqlumdash/sqlite/tool/rowlock_cleaner.c', needed by 'sqlumdash_cleaner'.  Stop.
```

```
 $ tail  ./../patch/sqlumdash.patch 
  +   rowlock_os_linux.c
  +   rowlock_os_win.c
  +   rowlock_pager.c
  +   rowlock_savepoint.c
  +
      parse.c
   
      tokenize.c
  SQLumDash3.26.0/tool のみに存在: rowlock_cleaner.c
  SQLumDash3.26.0/tool/win のみに存在: uniq.bat
```

**Comment by t-kataym** [comment]
Thank you for reporting.
Could you copy necessary files by executing the following commands before make?
```sh
  $ cp src/* sqlite/src/
  $ cp -R tool/* sqlite/tool/
  $ cp test/* sqlite/test/
```
You can know how to build SQLumDash by README.md: 1-2. Copy new files.
(I will modify the style of the description because it is hard to read it now.)

**Comment by iwamatsu** [comment]
Oh, sorry.
I did not copy a file  from test dir.
Thanks for your help.
